/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.content-top[_ngcontent-%COMP%]{padding-top:13px;padding-bottom:27px}h1.al-title[_ngcontent-%COMP%]{font-weight:700;color:#fff;float:left;width:auto;margin:0;padding:0;font-size:24px;text-transform:uppercase;opacity:0.9}.al-breadcrumb[_ngcontent-%COMP%]{background:none;color:#fff;padding:0;margin:0;float:right;padding-top:11px}.al-breadcrumb[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{font-size:18px;font-weight:400}.al-breadcrumb[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{color:#4dc4ff}.al-breadcrumb[_ngcontent-%COMP%]   li.breadcrumb-item.active[_ngcontent-%COMP%]{color:#fff}.al-look[_ngcontent-%COMP%]{float:right;margin-right:10px;padding-top:10px}.al-look[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]{font-size:19px}'];
//# sourceMappingURL=baContentTop.scss.shim.ngstyle.js.map