/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.ba-back-top[_ngcontent-%COMP%]{position:fixed;width:52px;height:52px;cursor:pointer;z-index:9999;display:none;text-decoration:none;right:40px;bottom:40px !important;font-size:45px;text-align:center;opacity:0.4;color:#00abff;background-color:rgba(0,0,0,0.75);border-radius:50%;line-height:46px}.ba-back-top[_ngcontent-%COMP%]:hover{opacity:0.8}'];
//# sourceMappingURL=baBackTop.scss.shim.ngstyle.js.map